---
- name: Install Postgresql server
  ansible.builtin.package:
    name: postgresql
    state: present

- name: Enable postgresql service
  systemd:
    name: postgresql.service
    enabled: true
    masked: no

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: postgresql

- name: Install python3 and pip
  ansible.builtin.package:
    name:
      - python3
      - python3-psycopg2
    state: present

- name: Set Postgresql listening TCP-connections
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "*"
  become: true
  become_user: postgres
  notify: restart postgresql-server

- name: Set timezone parameter
  community.postgresql.postgresql_set:
    name: TimeZone
    value: "{{ timezone }}"
  become: true
  become_user: postgres

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "{{ pg_conf_dir }}/pg_hba.conf"
    contype: local
    databases: all
    users: "postgres"
    method: peer
    create: true
  become: true
  become_user: postgres
  notify: restart postgresql-server

- name: Revoke access from local user all on database all.
  postgresql_pg_hba:
    dest: "{{ pg_conf_dir }}/pg_hba.conf"
    contype: local
    users: all
    databases: all
    state: absent
  become: true
  become_user: postgres
  notify: restart postgresql-server