- name: Gunicorn config template file
  ansible.builtin.template:
    src: "gunicorn.config.py.j2"
    dest: "/home/{{ app_name }}/gunicorn.config.py"
    owner: "{{ app_name }}"
    group: www-data
    mode: "0644"

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "/var/{{ item }}"
    state: directory
    owner: "{{ app_name }}"
    group: www-data
    mode: '0644'
  with_items:
    - log/gunicorn
    - run/gunicorn
  
- name: .env file
  ansible.builtin.template:
    src: ".env.j2"
    dest: "/home/{{ app_name }}/app/.env"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "{{ app_name }} systemd service file"
  ansible.builtin.template:
    src: "daemon.service.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: "root"
    group: "root"
    mode: "0664"

- name: Run migrations
  shell: "source /home/{{ app_name }}/app/venv/bin/activate && python /home/{{ app_name }}/app/manage.py migrate"
  args:
    executable: /bin/bash
  become: true

- name:  "Start {{ app_name }}.service"
  ansible.builtin.systemd:
    name: "{{ app_name }}"
    state: started
